esp_toml_version = 1.0

# This should be a publicly accessible URL of the file server where your firmware binaries are available for download
firmware_images_url = "https://dl.espressif.com/AE/esp-box/"

supported_apps = ["ESP-BOX_Demo_EN_V0.3.0"]

[ESP-BOX_Demo_EN_V0.3.0]
# ESP32 Chipsets for which you have a supported Firmware App. Define a property for each supported chipset in the given format.
chipsets = ["ESP32-S3"]
# Configure the name of the binary file
image.esp32-s3 = "ESP-BOX_Demo_EN_V0.3.0.bin"
android_app_url = ""
ios_app_url = ""
